version: '3'
services:
  php-fpm:
    build:
      context: ./frontend/docker
      dockerfile: php-fpm.docker
    volumes:
      - ../test:/var/www/test
    depends_on:
      - postgres-test
  frontend-nginx:
    build:
      context: ./frontend/docker
      dockerfile: nginx.docker
    volumes:
      - ../test:/var/www/test
    ports:
      - "8011:80"
    depends_on:
      - php-fpm
  backend-nginx:
    build:
      context: ./backend/docker
      dockerfile: nginx.docker
    volumes:
      - ../test:/var/www/test
    ports:
      - "8012:80"
    depends_on:
      - frontend-nginx
  postgres-test:
    image: postgres:9.6-alpine
    volumes:
      - ./common/var/docker/postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=testtest"
      - "POSTGRES_PASSWORD=testtest"
      - "POSTGRES_DB=testtest"
    ports:
      - "54324:5432"
  php-cli:
    build:
      context: ./common/docker
      dockerfile: php-cli.docker
    volumes:
      - ../test:/var/www/test
    depends_on:
      - postgres-test
    working_dir: /var/www/test
    tty: true